const students = [{
  "id": 1,
  "first_name": "Sheelagh",
  "last_name": "Maestro",
  "age": 18,
  "email": "smaestro0@techcrunch.com",
  "gender": "Female",
  "phone_number": "867-227-7031",
  "gpa": 1.91,
  "major": "Information Technology",
  "address": "97 Scoville Lane",
  "graduation_date": "04-12-2020",
  "city": "Naagas"
}, {
  "id": 2,
  "first_name": "Charlot",
  "last_name": "Makey",
  "age": 24,
  "email": "cmakey1@epa.gov",
  "gender": "Female",
  "phone_number": "968-121-3183",
  "gpa": 1.42,
  "major": "Maths",
  "address": "46470 6th Lane",
  "graduation_date": "20-05-2020",
  "city": "Rawa"
}, {
  "id": 3,
  "first_name": "Johnathan",
  "last_name": "Klaaasen",
  "age": 22,
  "email": "jklaaasen2@live.com",
  "gender": "Male",
  "phone_number": "308-542-6395",
  "gpa": 3.24,
  "major": "Mechanical Engineering",
  "address": "0626 Sage Circle",
  "graduation_date": "28-06-2020",
  "city": "Boucinha"
}, {
  "id": 4,
  "first_name": "Cindi",
  "last_name": "Ellesworthe",
  "age": 20,
  "email": "cellesworthe3@xing.com",
  "gender": "Female",
  "phone_number": "463-836-1450",
  "gpa": 0.08,
  "major": "Maths",
  "address": "85 Pleasure Park",
  "graduation_date": "09-07-2022",
  "city": "Isfara"
}, {
  "id": 5,
  "first_name": "Garrott",
  "last_name": "Flacknoe",
  "age": 24,
  "email": "gflacknoe4@soundcloud.com",
  "gender": "Male",
  "phone_number": "947-479-6631",
  "gpa": 2.94,
  "major": "Electrical Engineering",
  "address": "0924 Kropf Point",
  "graduation_date": "05-05-2023",
  "city": "Davao"
}, {
  "id": 6,
  "first_name": "Hughie",
  "last_name": "Brattell",
  "age": 21,
  "email": "hbrattell5@imdb.com",
  "gender": "Male",
  "phone_number": "105-768-4842",
  "gpa": 3.21,
  "major": "Information Technology",
  "address": "54042 Debra Point",
  "graduation_date": "17-11-2020",
  "city": "Oelaba"
}, {
  "id": 7,
  "first_name": "Kellsie",
  "last_name": "Goring",
  "age": 18,
  "email": "kgoring6@fda.gov",
  "gender": "Female",
  "phone_number": "415-564-6297",
  "gpa": 3.33,
  "major": "Electrical Engineering",
  "address": "2657 Fuller Street",
  "graduation_date": "18-08-2021",
  "city": "Renfrew"
}, {
  "id": 8,
  "first_name": "Xylia",
  "last_name": "McMurthy",
  "age": 23,
  "email": "xmcmurthy7@technorati.com",
  "gender": "Female",
  "phone_number": "179-445-0401",
  "gpa": 2.69,
  "major": "Chemistry",
  "address": "92 Crowley Drive",
  "graduation_date": "19-05-2023",
  "city": "Guayabo Dulce"
}, {
  "id": 9,
  "first_name": "Ladonna",
  "last_name": "Bover",
  "age": 23,
  "email": "lbover8@elegantthemes.com",
  "gender": "Female",
  "phone_number": "262-718-4189",
  "gpa": 1.72,
  "major": "Mechanical Engineering",
  "address": "3543 Bobwhite Lane",
  "graduation_date": "08-07-2021",
  "city": "Hekou"
}, {
  "id": 10,
  "first_name": "Pansie",
  "last_name": "Pendergrast",
  "age": 21,
  "email": "ppendergrast9@seesaa.net",
  "gender": "Female",
  "phone_number": "180-398-7118",
  "gpa": 1.64,
  "major": "Physics",
  "address": "5 Lakewood Street",
  "graduation_date": "17-03-2021",
  "city": "Ipatinga"
}, {
  "id": 11,
  "first_name": "Dolli",
  "last_name": "Thew",
  "age": 19,
  "email": "dthewa@nytimes.com",
  "gender": "Female",
  "phone_number": "283-428-7357",
  "gpa": 0.17,
  "major": "Mechanical Engineering",
  "address": "6035 Village Drive",
  "graduation_date": "20-06-2020",
  "city": "Cinyawar"
}, {
  "id": 12,
  "first_name": "Carce",
  "last_name": "Etchells",
  "age": 18,
  "email": "cetchellsb@imdb.com",
  "gender": "Male",
  "phone_number": "847-671-9428",
  "gpa": 3.63,
  "major": "Physics",
  "address": "51926 Spaight Alley",
  "graduation_date": "27-02-2020",
  "city": "‘Arad"
}, {
  "id": 13,
  "first_name": "Ebony",
  "last_name": "Grzegorecki",
  "age": 25,
  "email": "egrzegoreckic@nytimes.com",
  "gender": "Female",
  "phone_number": "515-892-8459",
  "gpa": 0.64,
  "major": "Chemistry",
  "address": "1459 Ridgeview Circle",
  "graduation_date": "05-12-2022",
  "city": "Burrel"
}, {
  "id": 14,
  "first_name": "Lyda",
  "last_name": "Dows",
  "age": 25,
  "email": "ldowsd@constantcontact.com",
  "gender": "Female",
  "phone_number": "163-926-5194",
  "gpa": 0.8,
  "major": "Computer Science Engineering",
  "address": "65746 Chive Park",
  "graduation_date": "12-06-2020",
  "city": "Mushu"
}, {
  "id": 15,
  "first_name": "Trueman",
  "last_name": "Sich",
  "age": 21,
  "email": "tsiche@google.com.hk",
  "gender": "Male",
  "phone_number": "868-858-9866",
  "gpa": 1.3,
  "major": "Electrical Engineering",
  "address": "6 Anderson Park",
  "graduation_date": "10-05-2023",
  "city": "Aegela"
}, {
  "id": 16,
  "first_name": "Porter",
  "last_name": "Lynskey",
  "age": 23,
  "email": "plynskeyf@reference.com",
  "gender": "Male",
  "phone_number": "639-318-6061",
  "gpa": 3.32,
  "major": "Chemistry",
  "address": "30412 Dakota Street",
  "graduation_date": "12-11-2020",
  "city": "Hodkovice nad Mohelkou"
}, {
  "id": 17,
  "first_name": "Angelita",
  "last_name": "Moloney",
  "age": 19,
  "email": "amoloneyg@java.com",
  "gender": "Female",
  "phone_number": "279-664-3706",
  "gpa": 0.96,
  "major": "Chemistry",
  "address": "8356 Iowa Court",
  "graduation_date": "31-03-2021",
  "city": "Gorzów Śląski"
}, {
  "id": 18,
  "first_name": "Amery",
  "last_name": "Tzuker",
  "age": 22,
  "email": "atzukerh@xinhuanet.com",
  "gender": "Male",
  "phone_number": "275-432-5768",
  "gpa": 0.42,
  "major": "Physics",
  "address": "76774 Loftsgordon Parkway",
  "graduation_date": "08-06-2022",
  "city": "Praia da Vagueira"
}, {
  "id": 19,
  "first_name": "Catriona",
  "last_name": "Records",
  "age": 25,
  "email": "crecordsi@google.com.hk",
  "gender": "Female",
  "phone_number": "266-418-6478",
  "gpa": 2.47,
  "major": "Biology",
  "address": "00063 Dryden Center",
  "graduation_date": "10-06-2022",
  "city": "Tekes"
}, {
  "id": 20,
  "first_name": "Cosimo",
  "last_name": "Loynton",
  "age": 19,
  "email": "cloyntonj@infoseek.co.jp",
  "gender": "Male",
  "phone_number": "133-843-3181",
  "gpa": 0.26,
  "major": "Chemistry",
  "address": "28 Burning Wood Parkway",
  "graduation_date": "03-08-2023",
  "city": "Machala"
}, {
  "id": 21,
  "first_name": "Frasco",
  "last_name": "Hawler",
  "age": 24,
  "email": "fhawlerk@icio.us",
  "gender": "Male",
  "phone_number": "573-883-5224",
  "gpa": 0.21,
  "major": "Mechanical Engineering",
  "address": "335 Jana Street",
  "graduation_date": "27-12-2021",
  "city": "Omigawa"
}, {
  "id": 22,
  "first_name": "Cash",
  "last_name": "Hylden",
  "age": 18,
  "email": "chyldenl@businesswire.com",
  "gender": "Male",
  "phone_number": "769-574-2570",
  "gpa": 2.62,
  "major": "Computer Science Engineering",
  "address": "008 Barnett Lane",
  "graduation_date": "15-06-2021",
  "city": "Kuafeu"
}, {
  "id": 23,
  "first_name": "Yanaton",
  "last_name": "Leipold",
  "age": 22,
  "email": "yleipoldm@artisteer.com",
  "gender": "Male",
  "phone_number": "806-620-2878",
  "gpa": 1.69,
  "major": "Electrical Engineering",
  "address": "70 Summit Place",
  "graduation_date": "30-07-2022",
  "city": "Ban Selaphum"
}, {
  "id": 24,
  "first_name": "Claudie",
  "last_name": "Greatbanks",
  "age": 18,
  "email": "cgreatbanksn@google.it",
  "gender": "Female",
  "phone_number": "617-914-9397",
  "gpa": 3.78,
  "major": "Maths",
  "address": "84058 Cherokee Court",
  "graduation_date": "16-11-2021",
  "city": "Boston"
}, {
  "id": 25,
  "first_name": "Nickolas",
  "last_name": "Simper",
  "age": 22,
  "email": "nsimpero@illinois.edu",
  "gender": "Male",
  "phone_number": "770-617-9540",
  "gpa": 3.25,
  "major": "Biology",
  "address": "94 Donald Street",
  "graduation_date": "02-02-2023",
  "city": "Decatur"
}, {
  "id": 26,
  "first_name": "Fredek",
  "last_name": "Keling",
  "age": 24,
  "email": "fkelingp@usda.gov",
  "gender": "Male",
  "phone_number": "389-258-0798",
  "gpa": 1.06,
  "major": "Computer Science Engineering",
  "address": "44094 Valley Edge Street",
  "graduation_date": "26/06/2021",
  "city": "Feicheng"
}, {
  "id": 27,
  "first_name": "Eliot",
  "last_name": "Camellini",
  "age": 21,
  "email": "ecamelliniq@skype.com",
  "gender": "Male",
  "phone_number": "933-680-1351",
  "gpa": 1.91,
  "major": "Information Technology",
  "address": "995 Barby Point",
  "graduation_date": "27/02/2022",
  "city": "Krajan Alastengah"
}, {
  "id": 28,
  "first_name": "Reeba",
  "last_name": "Stansby",
  "age": 18,
  "email": "rstansbyr@ed.gov",
  "gender": "Female",
  "phone_number": "437-918-2032",
  "gpa": 2.02,
  "major": "Information Technology",
  "address": "867 Manley Plaza",
  "graduation_date": "06/02/2022",
  "city": "Loikaw"
}, {
  "id": 29,
  "first_name": "Giraldo",
  "last_name": "Spinelli",
  "age": 25,
  "email": "gspinellis@nasa.gov",
  "gender": "Male",
  "phone_number": "988-966-1162",
  "gpa": 0.28,
  "major": "Maths",
  "address": "11099 Bunting Place",
  "graduation_date": "29/08/2021",
  "city": "Satuek"
}, {
  "id": 30,
  "first_name": "Elinor",
  "last_name": "Kingsly",
  "age": 25,
  "email": "ekingslyt@washingtonpost.com",
  "gender": "Female",
  "phone_number": "751-842-8210",
  "gpa": 1.2,
  "major": "Physics",
  "address": "90155 Hansons Court",
  "graduation_date": "23/04/2020",
  "city": "Sobreira"
}, {
  "id": 31,
  "first_name": "Sauveur",
  "last_name": "Cowthard",
  "age": 20,
  "email": "scowthardu@zimbio.com",
  "gender": "Male",
  "phone_number": "356-464-3662",
  "gpa": 1.92,
  "major": "Computer Science Engineering",
  "address": "42 Grim Point",
  "graduation_date": "24/10/2023",
  "city": "Panjakent"
}, {
  "id": 32,
  "first_name": "Parrnell",
  "last_name": "Bramall",
  "age": 25,
  "email": "pbramallv@theatlantic.com",
  "gender": "Male",
  "phone_number": "149-995-2756",
  "gpa": 0.84,
  "major": "Electrical Engineering",
  "address": "815 Moulton Way",
  "graduation_date": "16/04/2022",
  "city": "Escazú"
}, {
  "id": 33,
  "first_name": "Bradley",
  "last_name": "Lockner",
  "age": 24,
  "email": "blocknerw@trellian.com",
  "gender": "Male",
  "phone_number": "280-906-6100",
  "gpa": 2.51,
  "major": "Information Technology",
  "address": "7 Oak Valley Circle",
  "graduation_date": "25/10/2021",
  "city": "Ranot"
}, {
  "id": 34,
  "first_name": "Erhard",
  "last_name": "Cordet",
  "age": 18,
  "email": "ecordetx@is.gd",
  "gender": "Male",
  "phone_number": "711-193-8236",
  "gpa": 1.12,
  "major": "Information Technology",
  "address": "4085 Toban Crossing",
  "graduation_date": "24/04/2023",
  "city": "Rymanów"
}, {
  "id": 35,
  "first_name": "Cesar",
  "last_name": "Rosencwaig",
  "age": 25,
  "email": "crosencwaigy@webeden.co.uk",
  "gender": "Male",
  "phone_number": "198-715-6560",
  "gpa": 2.63,
  "major": "Information Technology",
  "address": "73 Springview Pass",
  "graduation_date": "14/01/2023",
  "city": "Conchamarca"
}, {
  "id": 36,
  "first_name": "Kristel",
  "last_name": "Reisenberg",
  "age": 24,
  "email": "kreisenbergz@va.gov",
  "gender": "Female",
  "phone_number": "578-875-5654",
  "gpa": 2.88,
  "major": "Computer Science Engineering",
  "address": "64454 Northview Circle",
  "graduation_date": "24/02/2020",
  "city": "Kudinovo"
}, {
  "id": 37,
  "first_name": "Rowney",
  "last_name": "World",
  "age": 19,
  "email": "rworld10@cdc.gov",
  "gender": "Male",
  "phone_number": "376-531-9155",
  "gpa": 0.19,
  "major": "Computer Science Engineering",
  "address": "1 Northridge Lane",
  "graduation_date": "09/07/2023",
  "city": "Bernay"
}, {
  "id": 38,
  "first_name": "Dicky",
  "last_name": "Burnage",
  "age": 18,
  "email": "dburnage11@nytimes.com",
  "gender": "Male",
  "phone_number": "952-649-2962",
  "gpa": 2.84,
  "major": "Information Technology",
  "address": "8 Wayridge Street",
  "graduation_date": "04/08/2020",
  "city": "Chongjin"
}, {
  "id": 39,
  "first_name": "Wright",
  "last_name": "Blatcher",
  "age": 21,
  "email": "wblatcher12@who.int",
  "gender": "Male",
  "phone_number": "181-387-0141",
  "gpa": 0.58,
  "major": "Biology",
  "address": "99 Washington Lane",
  "graduation_date": "14/02/2020",
  "city": "Olutanga"
}, {
  "id": 40,
  "first_name": "Baldwin",
  "last_name": "Jaquiss",
  "age": 25,
  "email": "bjaquiss13@shop-pro.jp",
  "gender": "Male",
  "phone_number": "490-487-4151",
  "gpa": 2.41,
  "major": "Chemistry",
  "address": "3 Daystar Street",
  "graduation_date": "15/04/2020",
  "city": "Maramag"
}, {
  "id": 41,
  "first_name": "Karlee",
  "last_name": "Merioth",
  "age": 25,
  "email": "kmerioth14@oaic.gov.au",
  "gender": "Female",
  "phone_number": "408-458-3450",
  "gpa": 0.01,
  "major": "Computer Science Engineering",
  "address": "32 Glacier Hill Trail",
  "graduation_date": "22/02/2020",
  "city": "Ýpsonas"
}, {
  "id": 42,
  "first_name": "Philip",
  "last_name": "Halgarth",
  "age": 24,
  "email": "phalgarth15@dagondesign.com",
  "gender": "Male",
  "phone_number": "527-149-2512",
  "gpa": 2.2,
  "major": "Information Technology",
  "address": "6 Ohio Hill",
  "graduation_date": "02/03/2021",
  "city": "Jinzipai"
}, {
  "id": 43,
  "first_name": "Trumann",
  "last_name": "Labes",
  "age": 23,
  "email": "tlabes16@go.com",
  "gender": "Male",
  "phone_number": "820-710-0420",
  "gpa": 3.95,
  "major": "Mechanical Engineering",
  "address": "7 Muir Center",
  "graduation_date": "05/05/2023",
  "city": "Puerto Boyacá"
}, {
  "id": 44,
  "first_name": "Cele",
  "last_name": "Elder",
  "age": 18,
  "email": "celder17@yolasite.com",
  "gender": "Female",
  "phone_number": "288-228-2671",
  "gpa": 3.24,
  "major": "Maths",
  "address": "359 Fairview Point",
  "graduation_date": "30/07/2020",
  "city": "Titay"
}, {
  "id": 45,
  "first_name": "Dennis",
  "last_name": "Crimes",
  "age": 22,
  "email": "dcrimes18@bbc.co.uk",
  "gender": "Male",
  "phone_number": "589-364-4963",
  "gpa": 0.06,
  "major": "Information Technology",
  "address": "75554 Larry Plaza",
  "graduation_date": "22/09/2022",
  "city": "Liulihe"
}, {
  "id": 46,
  "first_name": "Mallory",
  "last_name": "Asbrey",
  "age": 19,
  "email": "masbrey19@time.com",
  "gender": "Female",
  "phone_number": "447-867-0117",
  "gpa": 2.61,
  "major": "Mechanical Engineering",
  "address": "936 Susan Plaza",
  "graduation_date": "07/05/2023",
  "city": "Boawae"
}, {
  "id": 47,
  "first_name": "Cori",
  "last_name": "Kidde",
  "age": 24,
  "email": "ckidde1a@fda.gov",
  "gender": "Male",
  "phone_number": "451-638-0658",
  "gpa": 3.21,
  "major": "Information Technology",
  "address": "96982 Granby Junction",
  "graduation_date": "10/10/2020",
  "city": "Ksour Essaf"
}, {
  "id": 48,
  "first_name": "Lizabeth",
  "last_name": "Bamforth",
  "age": 19,
  "email": "lbamforth1b@webs.com",
  "gender": "Female",
  "phone_number": "279-478-9657",
  "gpa": 3.5,
  "major": "Mechanical Engineering",
  "address": "9 Park Meadow Place",
  "graduation_date": "11/10/2021",
  "city": "Darwin"
}, {
  "id": 49,
  "first_name": "Iorgos",
  "last_name": "Galfour",
  "age": 19,
  "email": "igalfour1c@weather.com",
  "gender": "Male",
  "phone_number": "516-867-0150",
  "gpa": 3.06,
  "major": "Physics",
  "address": "7326 Rusk Lane",
  "graduation_date": "26/10/2023",
  "city": "Slobodnica"
}, {
  "id": 50,
  "first_name": "Arnold",
  "last_name": "Mowett",
  "age": 23,
  "email": "amowett1d@sphinn.com",
  "gender": "Male",
  "phone_number": "426-958-1715",
  "gpa": 1.18,
  "major": "Information Technology",
  "address": "43058 Crownhardt Way",
  "graduation_date": "14/03/2021",
  "city": "Changtan"
}]
  
module.exports = students;